apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  selector:
    app: gitlab
  ports:
  - name: ui
    protocol: TCP
    port: 80
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/gitlab/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 2Gi
            cpu: 1
        volumeMounts:
          - mountPath: /var/opt/gitlab
            name: gitlab-pv-storage
      volumes:
        - name: gitlab-pv-storage
          persistentVolumeClaim:
            claimName: gitlab-pv-claim
